#!/bin/bash
#-------------------------------------------------------------------------------
#Modified by mkhaney mailto: michaelkhaney[at]gmail[dot]com
#Modified from helmuthdu mailto: helmuthdu[at]gmail[dot]com
#-------------------------------------------------------------------------------

# Create variable "nv" for target block device.
nv=/dev/nvme0n1

# Zero out all data structures of block device.
sgdisk -z $nv

# Create EFI boot, swap, root, and home partitions.
sgdisk -n 1::+1G -t 1:ef00 -c 1:boot $nv
sgdisk -n 2::+8G -t 2:8200 -c 2:swap $nv
sgdisk -n 3::+30G -t 3:8300 -c 3:root $nv
sgdisk -n 4::: -t 4:8300 -c 4:home $nv
sgdisk -p $nv
